---
sudo: false
language: ruby
cache: bundler
env:
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=6.0.0"
  - "RAILS_VERSION=6.1.0"
rvm:
  - 2.6.5
  - 2.7.2
  - 3.0.0
before_install: gem install bundler -v 1.17.3
matrix:
  fast_finish: true
